/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('primevue/button')['default']
    ButtonList: typeof import('./src/components/PageComponent/ButtonList.vue')['default']
    Column: typeof import('primevue/column')['default']
    DataTable: typeof import('primevue/datatable')['default']
    DatePicker: typeof import('primevue/datepicker')['default']
    FButton: typeof import('./src/components/Common/FButton.vue')['default']
    FButtonV2: typeof import('./src/components/Common/FButtonV2.vue')['default']
    FButtonV2Demo: typeof import('./src/components/Common/FButtonV2Demo.vue')['default']
    Home: typeof import('./src/components/PageComponent/Home.vue')['default']
    MultiSelect: typeof import('primevue/multiselect')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Skeleton: typeof import('primevue/skeleton')['default']
  }
}
