pipeline {
    agent any
    environment {
        // Gán IMAGE_VERSION bằng BUILD_NUMBER của Jenkins
        IMAGE_VERSION = "${env.BUILD_NUMBER}"
    }

    stages {
        stage('Git checkout stie, build and upload image to Registry') {
            steps {
                // sh 'git checkout $WORKSPACE'
                // sh 'git pull origin $WORKSPACE'
                script {
                    /* groovylint-disable-next-line NestedBlockDepth */
                    try {
                        /* groovylint-disable-next-line DuplicateStringLiteral, NestedBlockDepth */
                        if (params.WORKSPACE=="site-dev") {
                            sh 'bash ./cicd/build_image.sh $WORKSPACE ${WORKSPACE}-${IMAGES}  $IMAGE_VERSION ${URL_PRIVATE_REGISTRY}'
                            sh 'sudo docker images "${URL_PRIVATE_REGISTRY}/${WORKSPACE}-${IMAGES}" --digests'
                            currentBuild.result = 'SUCCESS'
                            // stage ('Building and uploading') {
                            //     sh 'bash ./cicd/build_image.sh $WORKSPACE ${WORKSPACE}-${IMAGES}  $IMAGE_VERSION ${URL_PRIVATE_REGISTRY}'
                            //     sh 'sudo docker images "${URL_PRIVATE_REGISTRY}/${WORKSPACE}-${IMAGES}" --digests'
                            //     currentBuild.result = 'SUCCESS'
                            // }
                        }
                        if (params.WORKSPACE=="site-staging") {
                            sh 'bash ./cicd/build_image.sh $WORKSPACE ${WORKSPACE}-${IMAGES}  $IMAGE_VERSION ${URL_PRIVATE_REGISTRY}'
                            sh 'sudo docker images "${URL_PRIVATE_REGISTRY}/${WORKSPACE}-${IMAGES}" --digests'
                            currentBuild.result = 'SUCCESS'
                            
                        }
                        if (params.WORKSPACE=="site-product") {
                            sh 'bash ./cicd/build_image.sh $WORKSPACE ${WORKSPACE}-${IMAGES}  $IMAGE_VERSION ${URL_PRIVATE_REGISTRY}'
                            sh 'sudo docker images "${URL_PRIVATE_REGISTRY}/${WORKSPACE}-${IMAGES}" --digests'
                            currentBuild.result = 'SUCCESS'
                            
                        }
                    }
                    catch (err) {
                        /* groovylint-disable-next-line DuplicateStringLiteral */
                        currentBuild.result = 'FAILURE'
                        echo 'BECOME SERVICES... exception occures!'
                    }
                    
                }
		    }
        }
        stage('Run Functional Test') {
            steps {
                script {
                    if (currentBuild.result == 'SUCCESS') {
                        currentBuild.result = 'SUCCESS'
                        echo 'Do not thing, auto pass...'
                    } else {
                        currentBuild.result = 'FAILURE'
                        echo 'FAILED IN TURNED APPLICATION TO SERVICES!'
                    }
                }
            }
        }
        stage('Running Perfomance') {
            steps {
                script {
                    if (currentBuild.result == 'SUCCESS') {
                        echo 'Do not thing, auto pass...'
                        currentBuild.result = 'SUCCESS'
                    } else {
                        currentBuild.result = 'FAILURE'
                        echo 'FAILED IN TURNED APPLICATION TO SERVICES!'
                    }
                }
            }
        }
	    stage('Promote to Deverloper') {
            steps {
                script {
                    if (currentBuild.result == 'SUCCESS') {
                        echo 'Runing ..'
                        sh 'bash ./cicd/update_image_to_service_on_k8s.sh $WORKSPACE ${WORKSPACE}-${IMAGES}  $IMAGE_VERSION ${URL_PRIVATE_REGISTRY}'
                    } else {
                        echo 'FAILED IN TURNED APPLICATION TO SERVICES!'
                    }
                }
            }
        }
        stage('Notify Telegram') {
            steps {
                script {
                    if (params.WORKSPACE=="site-product"){
                    // Telegram bot info
                    def telegramToken_2 = "5963974462:AAH4drQ2VL2BCvytrG0qAfPWoYZSH-nK0uE"       // Thay bằng token bot của bạn
                    def chatId_2 = "-1003806660301"              // Thay bằng chat ID group hoặc user
                    // Lấy tên người trigger build
                    // def logPath = "${env.JENKINS_HOME}/jobs/${env.JOB_NAME}/builds/${env.BUILD_NUMBER}/log"
                    // def startedBy = sh(
                    //     script: "grep -i 'Started by user' ${logPath} || true",
                    //     returnStdout: true
                    // ).trim()
                    // buildUser = startedBy.replaceFirst(/(?i)Started by user\s+/, "")
                    // def parts = buildUser.split(/\s+/)
                    // def lastTwo = parts.size() >= 3 ? parts[-2..-1].join(" ") : buildUser
                    def commitHash = sh(script: "git rev-parse --short HEAD", returnStdout: true).trim()
                    def commitMessage = sh(script: "git log -1 --pretty=%B", returnStdout: true).trim()
                    def commitAuthor = sh(script: "git log -1 --pretty=%an", returnStdout: true).trim()
                    def message = currentBuild.result == 'SUCCESS' ?
                    "✅ Build ${env.JOB_NAME}\nBuild number: #${env.BUILD_NUMBER} thành công!\nCommit Hash: ${commitHash}\nCommit Message: ${commitMessage}\ncommit Author: ${commitAuthor}\nConsole log: ${env.BUILD_URL}console" :
                    "❌ Build ${env.JOB_NAME}\nBuild number: #${env.BUILD_NUMBER} thất bại!\nCommit Hash: ${commitHash}\nCommit Message: ${commitMessage}\ncommit Author: ${commitAuthor}\nConsole log: ${env.BUILD_URL}console"
                    // Gửi message tới Telegram
                    sh """
                    curl -s -X POST "https://api.telegram.org/bot${telegramToken_2}/sendMessage" \
                    -d chat_id=${chatId_2} \
                    -d text="${message}"
                    """
                    } else {
                        echo "Ignore Send Notifacation deploy on workspace ${WORKSPACE}"
                    }
                }
            }
        }
        
    }
}
